#!/usr/bin/env python
# encoding: utf-8
import os
from pyftpdlib.authorizers import UnixAuthorizer
from pyftpdlib.filesystems import UnixFilesystem
from pyftpdlib.handlers import FTPHandler
from pyftpdlib.servers import FTPServer


def main():
    authorizer = UnixAuthorizer(
        rejected_users=['root'],
        require_valid_shell=True
    )
    handler = FTPHandler
    handler.authorizer = authorizer
    handler.abstracted_fs = UnixFilesystem
    server = FTPServer(('', int(os.environ.get('FTPD_PORT', '21'))), handler)
    server.serve_forever()


if __name__ == '__main__':
    main()
